defaults:
  - model: resnet50
  - _self_

architecture: ${model.name}
batch_size: 64
epochs: 50
lr: 0.001
weight_decay: 0.01
train_ratio: 0.7
warmup_epochs: 5
root_dir: data/NA_Fish_Dataset
logwandb : True