defaults:
  - model: resnet50
  - _self_

architecture: ${model.name}
batch_size: 64
epochs: 50
lr: 0.01
weight_decay: 0.001
train_ratio: 0.8
warmup_epochs: 5
root_dir: merged_dataset
log : True
seed : 42
aug : hard
n_images : 6
download_data : False
lr_factor: 10
restarts : False
patience: 10
delta : 0.001
n_workers : 4
wandb_entity : mohamedkhayat025-none
do_sample : False